services:
  - type: web
    name: gestao-mobilidade-saude
    runtime: python
    buildCommand: "./start.sh"
    startCommand: "gunicorn transporte_django.wsgi --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
