services:
  - type: web
    name: transporte-de-enfermos-2
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "./start.sh"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
