# Generated by Django 6.0.2 on 2026-04-29 16:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0002_mensagemwhatsapp"),
    ]

    operations = [
        migrations.AddField(
            model_name="paciente",
            name="oxigenio_litros_min",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Fluxo de O2 em litros por minuto",
                max_digits=4,
                null=True,
            ),
        ),
    ]
