# Generated by Django 6.0.4 on 2026-07-16 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0011_paciente_destino_preferencial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paciente",
            name="motivo_inativacao",
            field=models.CharField(
                blank=True,
                choices=[
                    ("alta", "Alta"),
                    ("obito", "Óbito"),
                    ("mudanca_cidade", "Mudança de cidade"),
                    ("nao_precisa", "Não necessita mais transporte"),
                    ("suspensao_temporaria", "Suspensão temporária"),
                    ("decisao_familiar", "Decisão familiar"),
                    ("retorno_servico", "Retorno ao serviço"),
                    ("outros", "Outros"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="servico_ativo",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Paciente apto a usar o serviço de transporte",
            ),
        ),
        migrations.AlterField(
            model_name="paciente",
            name="servico_status",
            field=models.CharField(
                choices=[
                    ("ativo", "Ativo"),
                    ("suspenso", "Suspenso temporariamente"),
                    ("encerrado", "Encerrado"),
                ],
                db_index=True,
                default="ativo",
                help_text="Status operacional do paciente no serviço de transporte",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="pacientestatushistorico",
            name="motivo",
            field=models.CharField(
                blank=True,
                choices=[
                    ("alta", "Alta"),
                    ("obito", "Óbito"),
                    ("mudanca_cidade", "Mudança de cidade"),
                    ("nao_precisa", "Não necessita mais transporte"),
                    ("suspensao_temporaria", "Suspensão temporária"),
                    ("decisao_familiar", "Decisão familiar"),
                    ("retorno_servico", "Retorno ao serviço"),
                    ("outros", "Outros"),
                ],
                max_length=30,
            ),
        ),
    ]
