# Generated by Django 6.0.2 on 2026-07-27 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0012_alter_paciente_motivo_inativacao_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Motorista",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
            ],
        ),
    ]
