# Generated by Django 6.0.2 on 2026-08-02 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0013_motorista"),
    ]

    operations = [
        migrations.AddField(
            model_name="paciente",
            name="data_nascimento",
            field=models.DateField(
                blank=True, help_text="Data de nascimento do paciente", null=True
            ),
        ),
    ]
