# Generated by Django 6.0.2 on 2026-08-15 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_paciente_data_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='patrimonio',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
