# Generated by Django 6.0.2 on 2026-08-30 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_alter_veiculo_patrimonio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bloco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(default=1, help_text='Número do bloco dentro da viagem (1, 2, 3...)')),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bloco',
                'verbose_name_plural': 'Blocos',
                'ordering': ['numero'],
            },
        ),
        migrations.AddField(
            model_name='transporte',
            name='ordem',
            field=models.PositiveIntegerField(default=0, help_text='Ordem do paciente dentro do bloco'),
        ),
        migrations.AddField(
            model_name='transporte',
            name='bloco',
            field=models.ForeignKey(blank=True, help_text='Bloco ao qual este paciente está alocado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transportes', to='polls.bloco'),
        ),
        migrations.CreateModel(
            name='Viagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(db_index=True)),
                ('numero', models.PositiveIntegerField(default=1, help_text='Número da viagem no dia (1ª, 2ª, 3ª...)')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('finalizado', 'Finalizado')], db_index=True, default='rascunho', max_length=15)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('condutor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viagens', to='polls.condutor')),
                ('enfermagem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viagens', to='polls.enfermagem')),
                ('veiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viagens', to='polls.veiculo')),
            ],
            options={
                'verbose_name': 'Viagem',
                'verbose_name_plural': 'Viagens',
                'ordering': ['data', 'numero'],
            },
        ),
        migrations.AddField(
            model_name='bloco',
            name='viagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocos', to='polls.viagem'),
        ),
    ]
