# Generated by Django 6.0.2 on 2026-08-31 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_bloco_transporte_ordem_transporte_bloco_viagem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='peso',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
