# Generated by Django 6.0.2 on 2026-09-11 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_alter_paciente_peso'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RotinaMapaViagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('origem', models.CharField(default='nem', max_length=20)),
                ('empresa', models.CharField(default='NEM', max_length=30)),
                ('padrao_agendamento', models.CharField(default='data_unica', max_length=20)),
                ('data_final', models.DateField(blank=True, null=True)),
                ('apenas_dias_uteis', models.BooleanField(default=False)),
                ('numero_viagem', models.CharField(default='1ª Viagem', max_length=20)),
                ('horario_consulta', models.TimeField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('paciente_ids_json', models.JSONField(blank=True, default=list)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('condutor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rotinas_mapa_viagem', to='polls.condutor')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotinas_mapa_viagem', to=settings.AUTH_USER_MODEL)),
                ('veiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rotinas_mapa_viagem', to='polls.veiculo')),
            ],
            options={
                'ordering': ['nome'],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'nome'), name='uniq_rotina_mapa_viagem_usuario_nome')],
            },
        ),
    ]
